export const selectors = [
  'top-panel-explore-Marketplace',
  'top-panel-explore-Games',
  'top-panel-explore-Pages',
  'create-post-panel-safety-just-me',
  'create-post-panel-safety-friends',
  'explore-1',
  'explore-2',
  'explore-4',
  'explore-5',
  'explore-6',
  'explore-7',
  'explore-8',
  'explore-9',
  'explore-10',
  'explore-13',
  'explore-17',
  'explore-18',
  'explore-20',
  'post-settings-save',
  'post-settings-hide',
  'post-settings-notifications',
  'composer-tag-friends',
  'composer-check-in',
  'composer-add-pic',
  'composer-background-button',
  'composer-feeling',
  'composer-recommendation',
  'composer-gif',
  'composer-charity',
  'composer-live-stream',
  'create-post-more',
  'stories',
  'videoChats',
  'right-panel-sponsored',
  'friends-recommended',
  'friends-games',
  'friends-games-popular',
]

export const actions = {
  ABORT: 'abort',
  EXIT: 'exit',
  DONE: 'done',
  FORWARD: 'forward',
  BACKWARD: 'backward',
  JUMP_TO: 'jump-to',
  SELECTION: 'selection',
  CHECK: 'check',
  HELP_PANEL: 'help-panel',
  CONTACT_EDIT: 'contact-edit',
}

export default {
  actions,
  selectors,
}
