name: create-release-on-pushing-tag

on:
  # [push]
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: all da shitz!
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout code
        uses: actions/checkout@master
        # with:
        #   fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      # - run: cd facebook-for-elderly
      - name: Install dependencies
        run: |
          npm install
      - name: Add app key
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'PARSE_APP_KEY' # [Required]
          value: ${{secrets.PARSE_APP_KEY}} # [Required]
          nullable: 'false' # [Optional] if the resolved value is empty, the variable will be omitted
          envPath: '.env' # [Optional] The path to the dotenv file (defaults to `.env`)
      - name: Add javascript key
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'PARSE_JAVASCRIPT_KEY' # [Required]
          value: ${{secrets.PARSE_JAVASCRIPT_KEY}} # [Required]
          nullable: 'false' # [Optional] if the resolved value is empty, the variable will be omitted
          envPath: '.env' # [Optional] The path to the dotenv file (defaults to `.env`)
      - name: build
        run: |
          npm run build chrome
          npm run build firefox
      - name: Create new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          #           body: |
          #             Changes in this Release
          #             - First Change
          #             - Second Change
          draft: false
          prerelease: false
      - name: Upload Chrome zip
        id: upload-release-chrome
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./packages/facebook-for-digital-seniors.${{ steps.get_version.outputs.VERSION }}.chrome.zip
          asset_name: facebook-for-digital-seniors.${{ steps.get_version.outputs.VERSION }}.chrome.zip
          asset_content_type: application/zip
      - name: Upload Firefox zip
        id: upload-release-firefox
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./packages/facebook-for-digital-seniors.${{ steps.get_version.outputs.VERSION }}.firefox.xpi.zip
          asset_name: facebook-for-digital-seniors.${{ steps.get_version.outputs.VERSION }}.firefox.xpi.zip
          asset_content_type: application/zip
